package com.example.themlexplorer.ui.europeLandmarkRecognizer.domain

/**
 * Classification an data class holds the output generated by the model when it analysis the input completely.
 */
data class Classification(
    val name: String,
    val score: Float
)
